# Generated by Django 5.0 on 2023-12-16 06:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_habit', models.CharField(max_length=80, verbose_name='Место выполнения привычки')),
                ('time_habit', models.TimeField(verbose_name='Время привычки')),
                ('get_habit', models.CharField(max_length=200, verbose_name='Что делаем(например, приседаем)')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('associated_habit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Приятная связанная привычка ')),
                ('period_habit', models.CharField(choices=[('Каждый день', 'Каждый день'), ('Один раз в неделю', 'Один раз в неделю'), ('Два раза в неделю', 'Два раза в неделю'), ('Три раза в неделю', 'Три раза в неделю'), ('Четыре раза в неделю', 'Четыре раза в неделю'), ('Пять раз в неделю', 'Пять раз в неделю'), ('Шесть раз в неделю', 'Шесть раз в неделю')], verbose_name='Периодичность')),
                ('reward_habit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Награда за выполнение привычки')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='продолжительность выполнения')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичность')),
                ('next_reminder_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата следующего напоминания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
