# Generated by Django 5.0 on 2024-01-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='next_reminder_date',
        ),
        migrations.AddField(
            model_name='habit',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 9, 9, 15, 34, 591266, tzinfo=datetime.timezone.utc), verbose_name='дата и время создания привычки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='period_habit',
            field=models.CharField(choices=[('Каждый день', 'Каждый день'), ('Раз в два дня', 'Раз в два дня'), ('Раз в три дня', 'Раз в три дня')], verbose_name='Периодичность'),
        ),
    ]
