# Generated by Django 5.0 on 2024-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_next_reminder_date_habit_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='дата и время создания привычки'),
        ),
    ]
