# Generated by Django 5.0 on 2024-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_habit',
            field=models.TimeField(default='12:00', verbose_name='Время привычки'),
        ),
    ]
